### ISSUE TITLE
git meta open $nonexistent gives a stack trace

### ISSUE THREAD

**Issue by novalis** [twosigma/git-meta#194]
git meta open fleem
fleem does not exist.
AssertionError: expected undefined to be a string
    at Function.assert.isString (/home/novalis/twosigma/git-meta/node/node_modules/chai/lib/chai/interface/assert.js:632:35)
    at submoduleNames.forEach.name (/home/novalis/twosigma/git-meta/node/lib/util/submodule_util.js:173:43)
    at Array.forEach (native)
    at Object.exports.getCurrentSubmoduleShas (/home/novalis/twosigma/git-meta/node/lib/util/submodule_util.js:173:20)
    at Object.<anonymous> (/home/novalis/twosigma/git-meta/node/lib/cmd/open.js:121:44)
    at next (native)
    at onFulfilled (/home/novalis/twosigma/git-meta/node/node_modules/co/index.js:65:19)
    at tryCallOne (/home/novalis/twosigma/git-meta/node/node_modules/nodegit-promise/lib/core.js:37:12)
    at /home/novalis/twosigma/git-meta/node/node_modules/nodegit-promise/lib/core.js:103:15
    at flush (/home/novalis/twosigma/git-meta/node/node_modules/asap/raw.js:50:29)

**Comment by bpeabody** [comment]
Should be fixed by https://github.com/twosigma/git-meta/pull/193
