### ISSUE TITLE
`git meta checkout $SHA` doesn't work 

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#386]
```
$ git meta checkout 7f5ce26bd6a671ca5cee22c5ccf148c3f68cb322
TypeError: Cannot read property 'commit' of undefined
    at Object.keys.forEach.name (lib/util/checkout.js:159:27)
    at Array.forEach (native)
    at lib/util/checkout.js:157:29
    at next (native)
    at onFulfilled (node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by bpeabody** [comment]
This seems to be resolved on `master`.
