### ISSUE TITLE
rebase error: "expected undefined to be a string"

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#395]
```
$ git meta rebase upstream/master
Rewinding to b778885450a39190a62b54cf34a705755d6407c3.
AssertionError: expected undefined to be a string
    at Function.assert.isString (node_modules/chai/lib/chai/interface/assert.js:632:35)
    at SubmoduleFetcher.<anonymous> (lib/util/submodule_fetcher.js:141:12)
    at next (native)
    at onFulfilled (node_modules/co/index.js:65:19)
    at node_modules/co/index.js:54:5
    at SubmoduleFetcher.co (node_modules/co/index.js:50:10)
    at SubmoduleFetcher.createPromise [as fetchSha] (node_modules/co/index.js:30:15)
    at lib/util/rebase_util.js:518:31
    at next (native)
    at onFulfilled (node_modules/co/index.js:65:19)
```

Note this happened when the onto branch pointed to a descendant of the current branch.

**Comment by bpeabody** [comment]
Addressed by https://github.com/twosigma/git-meta/pull/421
