### ISSUE TITLE
git meta checkout -b  needs something at refs/heads/* to exits to work.

### ISSUE THREAD

**Issue by zokir** [twosigma/git-meta#558]
`
$mkdir test_git_meta
$cd test_git_meta
$git init
$git remote add trunk someUrl
$git fetch trunk test_branch
$git meta checkout -b test_branch trunk/test_branch
Error: reference 'refs/heads/master' not found
    at Error (native)

$ git checkout -b test_branch trunk/test_branch
Branch 'test_branch' set up to track remote branch 'test_branch' from 'trunk'.
Switched to a new branch 'test_branch'
$cat .git/refs/heads/test_branch
3cf937dded80dc68444738c92919365ba11143b2

as soon as something in refs/hreads/ git meta works no problem:
$ git meta checkout -b test_branch2 trunk/test_branch
Created branch test_branch2.
Switched to branch test_branch2.
`

**Comment by bpeabody** [comment]
It fails differently (but still fails) on current master:

```bash
$ write-repos -o 'a=B:C2 s=Sb:1;Bfoo=2|b=B|x=N:Rtrunk=a foo=2'
6551:test$ cd x
6552:x$ git meta checkout -b test trunk/foo
AssertionError: expected null to be an instance of Commit
    at new SubmoduleFetcher (/Users/peabody/repos/git-meta/node/lib/util/submodule_fetcher.js:62:16)
    at /Users/peabody/repos/git-meta/node/lib/util/checkout.js:97:24
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/peabody/repos/git-meta/node/node_modules/co/index.js:65:19)
    at tryCallOne (/Users/peabody/repos/git-meta/node/node_modules/nodegit-promise/lib/core.js:37:12)
    at /Users/peabody/repos/git-meta/node/node_modules/nodegit-promise/lib/core.js:103:15
    at flush (/Users/peabody/repos/git-meta/node/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:150:11)
```

**Comment by bpeabody** [comment]
OK, after fixing that problem I see your bug, which probably is not related to the empty state of the repo.
