### ISSUE TITLE
git meta push origin unknown_branch fails with bar error. 

### ISSUE THREAD

**Issue by zokir** [twosigma/git-meta#607]
If branch does not exists locally, and we try to push, we get following error:

`
TypeError: Cannot read property 'id' of null
    at Object.<anonymous> (lib/util/push.js:226:32)
    at next (native)
    at onFulfilled (node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7
`

**Comment by novalis** [comment]
Legit -- we should say "no such branch" at that point.
