### ISSUE TITLE
Rather ambiguous error message on failure from git meta commit.

### ISSUE THREAD

**Issue by tslally** [twosigma/git-meta#704]
```bash
$ git meta commit -m 'Updated for commons io 2.6'
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at Object.exports.getSubmodulesFromWorkdir (/home/tsdist/vats_deployments/git-meta-ba29c1eb97feaebe7ceec34fc978a717564564ed/ext/public/twosigma/gitmeta/dist/lib/util/submodule_config_util.js:410:30)
    at Object.<anonymous> (/home/tsdist/vats_deployments/git-meta-ba29c1eb97feaebe7ceec34fc978a717564564ed/ext/public/twosigma/gitmeta/dist/lib/util/submodule_util.js:348:49)
    at Generator.next (<anonymous>)
    at onFulfilled (/home/tsdist/vats_deployments/git-meta-ba29c1eb97feaebe7ceec34fc978a717564564ed/ext/public/twosigma/gitmeta/dist/node_modules/co/index.js:65:19)
    at /home/tsdist/vats_deployments/git-meta-ba29c1eb97feaebe7ceec34fc978a717564564ed/ext/public/twosigma/gitmeta/dist/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (/home/tsdist/vats_deployments/git-meta-ba29c1eb97feaebe7ceec34fc978a717564564ed/ext/public/twosigma/gitmeta/dist/node_modules/co/index.js:50:10)
    at Object.createPromise [as listOpenSubmodules] (/home/tsdist/vats_deployments/git-meta-ba29c1eb97feaebe7ceec34fc978a717564564ed/ext/public/twosigma/gitmeta/dist/node_modules/co/index.js:30:15)
```

**Comment by tslally** [comment]
Sorted.  A submodule has its .`git/modules/submodule_path/config` set `bare = true`.
